---
controller:
  enableSnippets: true
  image:
    repository: private-registry.nginx.com/nginx-ic-nap-dos/nginx-plus-ingress
    tag: 3.0.2
    pullPolicy: Always
  nginxplus: true
  nginxStatus:
    allowCidrs: 0.0.0.0/0
    port: 9000
  readyStatus:
    initialDelaySeconds: 30
  serviceAccount:
    imagePullSecretName: regcred 
  service:
    type: ClusterIP
  reportIngressStatus:
    enable: true
    ingressLink: "${app}"
prometheus:
  create: true